In [2]:
import numpy as np

In [4]:
# read data from text files
with open('data/reviews.txt', 'r') as f:
    reviews = f.read()
with open('data/labels.txt', 'r') as f:
    labels = f.read()

In [5]:
print(reviews[:2000])
print()
print(labels[:20])

bromwell high is a cartoon comedy . it ran at the same time as some other programs about school life  such as  teachers  . my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers  . the scramble to survive financially  the insightful students who can see right through their pathetic teachers  pomp  the pettiness of the whole situation  all remind me of the schools i knew and their students . when i saw the episode in which a student repeatedly tried to burn down the school  i immediately recalled . . . . . . . . . at . . . . . . . . . . high . a classic line inspector i  m here to sack one of your teachers . student welcome to bromwell high . i expect that many adults of my age think that bromwell high is far fetched . what a pity that it isn  t   
story of a man who has unnatural feelings for a pig . starts out with a opening scene that is a terrific example of absurd comedy . a formal orchestra audience is turn

In [6]:
from string import punctuation

print(punctuation)

# get rid of punctuation
reviews = reviews.lower() # lowercase, standardize
all_text = ''.join([c for c in reviews if c not in punctuation])

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [7]:
# split by new lines and spaces
reviews_split = all_text.split('\n')
all_text = ' '.join(reviews_split)

# create a list of words
words = all_text.split()

In [8]:
words[:30]

['bromwell',
 'high',
 'is',
 'a',
 'cartoon',
 'comedy',
 'it',
 'ran',
 'at',
 'the',
 'same',
 'time',
 'as',
 'some',
 'other',
 'programs',
 'about',
 'school',
 'life',
 'such',
 'as',
 'teachers',
 'my',
 'years',
 'in',
 'the',
 'teaching',
 'profession',
 'lead',
 'me']

In [9]:
vocab_to_int = {word:i+1 for (i, word) in enumerate(set(words))}

reviews_ints = []
for text in reviews_split:
    reviews_ints.append([vocab_to_int[num] for num in text.split()])

In [10]:
# stats about vocabulary
print('Unique words: ', len((vocab_to_int)))  # should ~ 74000+
print()

# print tokens in first review
print('Tokenized review: \n', reviews_ints[:1])

Unique words:  74072

Tokenized review: 
 [[54344, 71045, 36957, 13135, 25958, 45677, 19006, 51256, 7246, 20586, 33398, 11612, 34985, 51241, 29768, 26911, 45036, 57150, 526, 38058, 34985, 46939, 25715, 51609, 71032, 20586, 28479, 39249, 10544, 36947, 38785, 43713, 47221, 54344, 71045, 27676, 47164, 36957, 66434, 61452, 38785, 4920, 47729, 36957, 46939, 20586, 59592, 38785, 19571, 644, 20586, 47874, 18950, 24970, 21302, 8134, 35822, 67532, 10508, 72550, 46939, 51357, 20586, 63103, 31340, 20586, 25922, 43958, 53918, 70616, 36947, 31340, 20586, 56557, 63840, 14569, 40895, 10508, 18950, 29797, 63840, 7681, 20586, 16073, 71032, 1470, 13135, 2603, 47022, 61168, 38785, 12588, 29584, 20586, 57150, 63840, 73917, 50680, 7246, 71045, 13135, 59290, 63842, 54834, 63840, 45418, 36116, 38785, 17766, 14420, 31340, 68863, 46939, 2603, 2184, 38785, 54344, 71045, 63840, 52525, 47221, 36386, 28341, 31340, 25715, 72730, 60047, 47221, 54344, 71045, 36957, 5398, 47688, 62079, 13135, 41617, 47221, 19006, 6403

In [11]:
encoded_labels = [1 if ch=="positive" else 0 if ch=="negative" else None for ch in labels.split("\n")]
encoded_labels

[1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,


In [12]:
from collections import Counter

# outlier review stats
review_lens = Counter([len(x) for x in reviews_ints])
print("Zero-length reviews: {}".format(review_lens[0]))
print("Maximum review length: {}".format(max(review_lens)))

Zero-length reviews: 1
Maximum review length: 2514


In [13]:
print('Number of reviews before removing outliers: ', len(reviews_ints))
print('Number of labels before removing outliers: ', len(encoded_labels))

# remove any reviews/labels with zero length from the reviews_ints list.

reviews_ints = [text for text in reviews_ints if len(text)!=0]
encoded_labels = [ele for ele in encoded_labels if ele!=None]

print('Number of reviews after removing outliers: ', len(reviews_ints))
print('Number of labels before removing outliers: ', len(encoded_labels))

Number of reviews before removing outliers:  25001
Number of labels before removing outliers:  25001
Number of reviews after removing outliers:  25000
Number of labels before removing outliers:  25000


In [14]:
reviews_ints[:3]

[[54344,
  71045,
  36957,
  13135,
  25958,
  45677,
  19006,
  51256,
  7246,
  20586,
  33398,
  11612,
  34985,
  51241,
  29768,
  26911,
  45036,
  57150,
  526,
  38058,
  34985,
  46939,
  25715,
  51609,
  71032,
  20586,
  28479,
  39249,
  10544,
  36947,
  38785,
  43713,
  47221,
  54344,
  71045,
  27676,
  47164,
  36957,
  66434,
  61452,
  38785,
  4920,
  47729,
  36957,
  46939,
  20586,
  59592,
  38785,
  19571,
  644,
  20586,
  47874,
  18950,
  24970,
  21302,
  8134,
  35822,
  67532,
  10508,
  72550,
  46939,
  51357,
  20586,
  63103,
  31340,
  20586,
  25922,
  43958,
  53918,
  70616,
  36947,
  31340,
  20586,
  56557,
  63840,
  14569,
  40895,
  10508,
  18950,
  29797,
  63840,
  7681,
  20586,
  16073,
  71032,
  1470,
  13135,
  2603,
  47022,
  61168,
  38785,
  12588,
  29584,
  20586,
  57150,
  63840,
  73917,
  50680,
  7246,
  71045,
  13135,
  59290,
  63842,
  54834,
  63840,
  45418,
  36116,
  38785,
  17766,
  14420,
  31340,
  68863,
  4

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
def pad_features(reviews_ints, seq_length):

    features = np.zeros([len(reviews_ints), seq_length])

    for i, review in enumerate(reviews_ints):
        if len(review) >= seq_length:
            features[i, :] = review[:seq_length]
        else:
            ind = seq_length - len(review)
            features[i, ind:] = review[:]

    return features

In [17]:
# Test your implementation!

seq_length = 200

features = pad_features(reviews_ints, seq_length=seq_length)

## test statements - do not change - ##
assert len(features)==len(reviews_ints), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."

# print first 10 values of the first 30 batches 
print(features[:30,:10])

[[    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [ 2521.  7697. 24253. 34985. 29795. 10703. 62190. 16973. 59577. 42627.]
 [39576. 23283. 34985. 13135. 38556. 72453. 27372. 62490. 36957. 33533.]
 [    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [29797. 63840. 35721.  9358. 25715. 63163. 10046. 36947. 16572. 38785.]
 [    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.]
 [20586. 46241. 45285. 38928. 13135. 72453. 57868. 

In [18]:
train_frac = 0.8
test_frac = 0.1

labels = np.array(encoded_labels)

num_train = int(len(features)*train_frac)
num_test = int(len(features)*test_frac)

train_x = features[:num_train, :]
train_y = labels[:num_train]

val_x = features[num_train:num_train+num_test, :]
val_y = labels[num_train:num_train+num_test]

test_x = features[num_train+num_test:, :]
test_y = labels[num_train+num_test:]

In [19]:
train_x.shape, val_x.shape, test_x.shape

((20000, 200), (2500, 200), (2500, 200))

In [20]:
train_y.shape, val_y.shape, val_y.shape

((20000,), (2500,), (2500,))

In [21]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))

# dataloaders
batch_size = 50

# make sure to SHUFFLE your data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

In [22]:
# obtain one batch of training data
dataiter = iter(train_loader)
sample_x, sample_y = next(dataiter)

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([50, 200])
Sample input: 
 tensor([[    0.,     0.,     0.,  ..., 18229., 19006., 31416.],
        [    0.,     0.,     0.,  ..., 23200., 73493., 63246.],
        [32641., 13135., 63041.,  ..., 53515., 13135., 55605.],
        ...,
        [    0.,     0.,     0.,  ..., 31340., 20586.,  1149.],
        [63840., 48134., 29588.,  ..., 10798., 51178., 66621.],
        [    0.,     0.,     0.,  ..., 36358.,  7246., 53918.]],
       dtype=torch.float64)

Sample label size:  torch.Size([50])
Sample label: 
 tensor([1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1], dtype=torch.int32)


In [24]:
use_cuda = torch.cuda.is_available()

In [25]:
import torch.nn as nn

In [26]:
vocab_size = len(vocab_to_int) + 1
vocab_size

74073

In [27]:
nn.Embedding(vocab_size, 400)

Embedding(74073, 400)

In [31]:


class SentimentRNN(nn.Module):

    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):

        super(SentimentRNN, self).__init__()

        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim

        # embedding and LSTM layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers,
                            dropout=drop_prob, batch_first=True)

        # dropout layer
        self.dropout = nn.Dropout(0.3)

        # linear and sigmoid layers
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sig = nn.Sigmoid()

    def forward(self, x, hidden):

        batch_size = x.size(0)

        # embedding and lstm_out
        x = x.long()
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)

        lstm_out = lstm_out[:, -1, :]

        # dropout
        out = self.dropout(lstm_out)
        out = self.fc(out)

        sig_out = self.sig(out)

        return sig_out, hidden

    def init_hidden(self, batch_size):

        weight = next(self.parameters()).data

        if use_cuda:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())

        return hidden

In [32]:
vocab_size = len(vocab_to_int) + 1
output_size = 1
embedding_dim = 400
hidden_dim = 256
n_layers = 2

net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)

print(net)

SentimentRNN(
  (embedding): Embedding(74073, 400)
  (lstm): LSTM(400, 256, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (sig): Sigmoid()
)


In [33]:
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=0.001)

In [35]:
epochs = 4

counter = 0
print_every = 100
clip=5 # gradient clipping

if use_cuda:
    net.cuda()

net.train()

for e in range(epochs):

    h = net.init_hidden(batch_size)

    for inputs, labels in train_loader:

        counter += 1

        if use_cuda:
            inputs, labels = inputs.cuda(), labels.cuda()

        h = tuple([each.data for each in h])

        # zero accumulated gradient
        net.zero_grad()

        # get the output from model
        output, h = net(inputs, h)

        # calculate the loss and perform backprop
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()

        # clip grad norm helps prevent the exploding gradient problem
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:

            val_h = net.init_hidden(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:

                val_h = tuple([each.data for each in val_h])

                if use_cuda:
                    inputs, labels = inputs.cuda(), labels.cuda()

                output, val_h = net(inputs, val_h)
                val_loss = criterion(output.squeeze(), labels.float())

                val_losses.append(val_loss.item())

            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 1/4... Step: 100... Loss: 0.548671... Val Loss: 0.694929


Epoch: 1/4... Step: 200... Loss: 0.679210... Val Loss: 0.694042
Epoch: 1/4... Step: 300... Loss: 0.673473... Val Loss: 0.635435
Epoch: 1/4... Step: 400... Loss: 0.666673... Val Loss: 0.542992
Epoch: 2/4... Step: 500... Loss: 0.434374... Val Loss: 0.505172
Epoch: 2/4... Step: 600... Loss: 0.529379... Val Loss: 0.447921
Epoch: 2/4... Step: 700... Loss: 0.342679... Val Loss: 0.441646
Epoch: 2/4... Step: 800... Loss: 0.488859... Val Loss: 0.476216
Epoch: 3/4... Step: 900... Loss: 0.149421... Val Loss: 0.517191
Epoch: 3/4... Step: 1000... Loss: 0.288185... Val Loss: 0.658518
Epoch: 3/4... Step: 1100... Loss: 0.159463... Val Loss: 0.492053
Epoch: 3/4... Step: 1200... Loss: 0.244141... Val Loss: 0.479490
Epoch: 4/4... Step: 1300... Loss: 0.071966... Val Loss: 0.566402
Epoch: 4/4... Step: 1400... Loss: 0.148028... Val Loss: 0.651843
Epoch: 4/4... Step: 1500... Loss: 0.252360... Val Loss: 0.578206
Epoch: 4/4... Step: 1600... Loss: 0.131678... Val Loss: 0.551360


In [37]:
test_losses = []
num_correct = 0

h = net.init_hidden(batch_size)

net.eval()


for inputs, labels in test_loader:

    h = tuple([each.data for each in h])

    if use_cuda:
        inputs, labels = inputs.cuda(), labels.cuda()

    output, h = net(inputs, h)

    # calculate loss
    test_loss = criterion(output.squeeze(), labels.float())
    test_losses.append(test_loss.item())

    # convert output probabilities to predict class (0 or 1)
    pred = torch.round(output.squeeze())

    # compare pred with true labels
    correct_tensor = pred.eq(labels.float().view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) if not use_cuda else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)

print("Test loss: {:.3f}".format(np.mean(test_losses)))

# accuracy over all test data
test_acc = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_acc))

Test loss: 0.544
Test accuracy: 0.811


In [39]:
# negative test review
test_review_neg = 'The worst movie I have seen; acting was terrible and I want my money back. This movie had bad acting and the dialogue was slow.'

In [40]:
from string import punctuation

def tokenize_review(test_review):
    test_review = test_review.lower() # lowercase
    # get rid of punctuation
    test_text = ''.join([c for c in test_review if c not in punctuation])

    # splitting by spaces
    test_words = test_text.split()

    # tokens
    test_ints = []
    test_ints.append([vocab_to_int.get(word, 0) for word in test_words])

    return test_ints

# test code and generate tokenized review
test_ints = tokenize_review(test_review_neg)
print(test_ints)

[[20586, 26000, 18639, 63840, 5731, 44240, 19694, 35721, 7313, 40895, 63840, 45098, 25715, 10181, 45343, 28087, 18639, 874, 14107, 19694, 40895, 20586, 54971, 35721, 3502]]


In [41]:
# test sequence padding
seq_length=200
features = pad_features(test_ints, seq_length)

print(features)

[[    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.     0.     0.     0.     0.

In [42]:
# test conversion to tensor and pass into your model
feature_tensor = torch.from_numpy(features)
print(feature_tensor.size())

torch.Size([1, 200])


In [46]:
def predict(net, test_review, sequence_length=200):
    
    net.eval()
    
    # tokenize review
    test_ints = tokenize_review(test_review)
    
    # pad tokenized sequence
    seq_length=sequence_length
    features = pad_features(test_ints, seq_length)
    
    # convert to tensor to pass into your model
    feature_tensor = torch.from_numpy(features)
    
    batch_size = feature_tensor.size(0)
    
    # initialize hidden state
    h = net.init_hidden(batch_size)
    
    if(use_cuda):
        feature_tensor = feature_tensor.cuda()
    
    # get the output from the model
    output, h = net(feature_tensor, h)
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze()) 
    # printing output value, before rounding
    print('Prediction value, pre-rounding: {:.6f}'.format(output.item()))
    
    # print custom response
    if(pred.item()==1):
        print("Positive review detected!")
    else:
        print("Negative review detected.")

In [47]:
# positive test review
test_review_pos = 'This movie had the best acting and the dialogue was so good. I loved it.'

In [48]:
# call function
seq_length=200 # good to use the length that was trained on

predict(net, test_review_neg, seq_length)

Prediction value, pre-rounding: 0.005533
Negative review detected.


In [49]:
# call function
seq_length=200 # good to use the length that was trained on

predict(net, test_review_pos, seq_length)

Prediction value, pre-rounding: 0.972495
Positive review detected!
